### PR TITLE
fix: items should show in bag table

### LINKED ISSUE #2: AAU, I should be able to move bags to "In Car" status.
I should be able to move bags to "In Car" status and this should also move all items in that bag as well. When a bag is moved to "In Car" status, users should be prevented from adding more items to that bag.

### PR DESCRIPTION
**Pull request by apc721**

### CODE REVIEW

File: src/BagStatus.tsx [hunk 1]
```diff
@@ -8,16 +8,32 @@ interface BagStatusProps {
...
+  const getBagItemsByNumber = async (bagId: number) => {
+    try {
+      const response = await axios.get(`http://localhost:8800/items/${bagId}`);
+      console.log(response.data);
+      const bagItems = response.data.map((item: any) => item.name);
+      return bagItems.join(", ");
+    }
+    catch (err) {
+      console.log(err);
+      return "";
```
Comment (apc721) [inline src/BagStatus.tsx]: Note for self: Do we want this return statement here?

File: src/BagStatus.tsx [hunk 2]
```diff
@@ -8,16 +8,32 @@ interface BagStatusProps {
...
 const BagStatus: React.FC<BagStatusProps> = ({ bags, deleteBag }) => {
+  const [bagItemsMap, setBagItemsMap] = useState<{ [key: number]: string }>({});
 
-  const getBagItemsByNumber = (bags: Bag[], bagId: number) => {
-    const bag = bags.find((bag) => bag.id === bagId);
-    return bag ? bag.items : [];
+  const getBagItemsByNumber = async (bagId: number) => {
+    try {
+      const response = await axios.get(`http://localhost:8800/items/${bagId}`);
+      console.log(response.data);
```
Comment (apc721) [inline src/BagStatus.tsx]: Remove console.log
